token-matcher:
  sync-time: 120s
  threads: 4
  threads-naming: 'Pool-TokenMatcher-Thread-%d'
  batch-size: 100

pathfinder:
  sync-time: 120s
  threads: 1
  threads-naming: 'Pool-Pathfinder-Thread-%d'

token-price-finder:
  sync-time: 2000s
  threads: 1
  threads-naming: 'Pool-TokenFinder-Thread-%d'

spring:
  datasource:
    url: ${TOKEN_MATCHER_DB_URL}
    username: ${TOKEN_MATCHER_DB_USER}
    password: ${TOKEN_MATCHER_DB_PASS}
    hikari:
      maximum-pool-size: 4