token-matcher:
  sync-time: 120s
  threads: 8

pathfinder:
  sync-time: 120s
  threads: 1

token-price-finder:
  sync-time: 2000s
  threads: 1

endpoint:
  cosmos-sdk:
    supply: '/cosmos/bank/v1beta1/supply'
    supply-paginated: '/cosmos/bank/v1beta1/supply?pagination.limit=1000000'
  ibc:
    denom-trace-beta: '/ibc/applications/transfer/v1beta1/denom_traces/%s'
    denom-trace: '/ibc/apps/transfer/v1/denom_traces/%s'
  coingecko:
    pro-api-key: ${PRO_API_KEY:null}
    base-url: 'https://api.coingecko.com/api/v3'
    token-price-history: '/coins/%s/market_chart/range?vs_currency=usd&from=%d&to=%d'
    pro-base-url: 'https://pro-api.coingecko.com/api/v3'
    pro-token-price-history: '/coins/%s/market_chart/range?vs_currency=usd&from=%d&to=%d&x_cg_pro_api_key='
  osmosis:
    base-url: 'https://api-osmosis.imperator.co'
    token-price-history-v2: '/tokens/v2/historical/%s/chart?tf=%d'

spring:
  main:
    web-application-type: none

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        jdbc:
          lob:
            non_contextual_creation: true