token-matcher:
  sync-time: 120s
  threads: 2
  threads-naming: 'Pool-TokenMatcher-Thread-%d'
  batch-size: 100
  endpoint: '/ibc/applications/transfer/v1beta1/denom_traces/%s'

pathfinder:
  sync-time: 120s
  threads: 2
  threads-naming: 'Pool-Pathfinder-Thread-%d'

spring:
  datasource:
    url: ${TOKEN_MATCHER_DB_URL}
    username: ${TOKEN_MATCHER_DB_USER}
    password: ${TOKEN_MATCHER_DB_PASS}
    hikari:
      maximum-pool-size: 4