token-matcher:
  sync-time: ${TM_SYNC_TIME}
  threads: ${TM_THREADS}

pathfinder:
  sync-time: ${PF_SYNC_TIME}
  threads: ${PF_THREADS}

token-price-finder:
  sync-time: ${TPF_SYNC_TIME}
  threads: ${TPF_THREADS}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 4