token-matcher:
  sync-time: 60s
  threads: 8
  threads-naming: 'Pool-TokenMatcher-Thread-%d'
  batch-size: 1000

pathfinder:
  sync-time: 20s
  threads: 1
  threads-naming: 'Pool-Pathfinder-Thread-%d'

token-price-finder:
  sync-time: 20s
  threads: 1
  threads-naming: 'Pool-TokenPriceFinder-Thread-%d'

endpoint:
  ibc:
    denom-trace: '/ibc/applications/transfer/v1beta1/denom_traces/%s'
  coingecko:
    base-url: 'https://api.coingecko.com/api/v3'
    token-price-history: '/coins/%s/market_chart?vs_currency=usd&days=%s&interval=hourly'

spring:
  main:
    web-application-type: none

    jpa:
      open-in-view: false

      hibernate:
        ddl-auto: validate

      properties:
        hibernate:
          schema_update:
            unique_constraint_strategy: RECREATE_QUIETLY
          jdbc:
            lob:
              non_contextual_creation: true