token-matcher:
  sync-time: 120s
  threads: 2

pathfinder:
  sync-time: 60s
  threads: 1

token-price-finder:
  sync-time: 10s
  threads: 1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moz_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4