token-matcher:
  sync-time: 120s
  threads: 16
  threads-naming: 'Pool-TokenMatcher-Thread-%d'
  batch-size: 1000

pathfinder:
  sync-time: 60s
  threads: 1
  threads-naming: 'Pool-Pathfinder-Thread-%d'

token-price-finder:
  sync-time: 60s
  threads: 1
  threads-naming: 'Pool-TokenFinder-Thread-%d'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moz_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 40