token-matcher:
  sync-time: 120s
  threads: 8
  threads-naming: 'Pool-TokenMatcher-Thread-%d'

pathfinder:
  sync-time: 120s
  threads: 1
  threads-naming: 'Pool-Pathfinder-Thread-%d'

token-price-finder:
  sync-time: 2000s
  threads: 1
  threads-naming: 'Pool-TokenPriceFinder-Thread-%d'

endpoint:
  ibc:
    denom-trace-beta: '/ibc/applications/transfer/v1beta1/denom_traces/%s'
    denom-trace: '/ibc/apps/transfer/v1/denom_traces/%s'
  coingecko:
    base-url: 'https://api.coingecko.com/api/v3'
    token-price-history: '/coins/%s/market_chart/range?vs_currency=usd&from=%d&to=%d'
  osmosis:
    base-url: 'https://api-osmosis.imperator.co'
    token-price-history-v2: '/tokens/v2/historical/%s/chart?tf=%d'

spring:
  main:
    web-application-type: none

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        jdbc:
          lob:
            non_contextual_creation: true